WebApplicationOne/WebApplicationOne/Entities/Mountain.cs
using System.ComponentModel;

namespace WebApplicationOne.Entities
{
    public class Mountain
    {
        public int MountainId { get; set; }
        [DisplayName("Nombre de la montaña")]
        public string Nombre { get; set; }
        [DisplayName("Altitud en metros")]
        public int Altitud { get; set; }
    }
}

WebApplicationOne/WebApplicationOne/Models/ErrorViewModel.cs
using System;

namespace WebApplicationOne.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplicationOne/WebApplicationOne/Controllers/CalculosController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplicationOne.Controllers
{
    public class CalculosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        // TODO: como acceder a Request.Form asp.net core 
        [HttpPost]
        public IActionResult Sumar(int primerNumero, int segundoNumero)
        {
            var primerNumeroFromBody = int.Parse(Request.Form["primerNumero"]);
            var segundoNumeroFromBody = int.Parse(Request.Form["segundoNumero"]);
            var resultadoFromBody = primerNumero + segundoNumero;

            var resultado = primerNumero + segundoNumero;

            ViewData["Resultado"] = resultado;
            ViewData["ResultadoFromBody"] = resultadoFromBody;
            
            return View();
        }
    }
}

WebApplicationOne/WebApplicationOne/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApplicationOne.Models;

namespace WebApplicationOne.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplicationOne/WebApplicationOne/Controllers/MountainsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using WebApplicationOne.Data;
using WebApplicationOne.Entities;

namespace WebApplicationOne.Controllers
{
    public class MountainsController : Controller
    {
        readonly MainDbContext _mainDbContext;
        public MountainsController(MainDbContext mainDbContext)
        {
            _mainDbContext = mainDbContext;
        }

        // GET: MountainsController
        public ActionResult Index()
        {
            List<Mountain> mountains = _mainDbContext.Mountains.ToList();
            return View(mountains);
        }

        // GET: MountainsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: MountainsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MountainsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Mountain mountain)
        {
            _mainDbContext.Add(mountain);
            var affected = _mainDbContext.SaveChanges();
            if (affected > 0)
                return RedirectToAction(nameof(Index));
            ViewData["Mensaje"] = "No se grabó";
            return View("Error");

        }

        // GET: MountainsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: MountainsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MountainsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: MountainsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplicationOne/WebApplicationOne/Views/Calculos/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Cáculos";
}

<div class="text-center">
    <h1>Cálculos</h1>
    <form action="/calculos/sumar" method="post">
        <div class="form-group">
            <input type="number" name="primerNumero" class="form-control" placeholder="Ingrese un número" />
        </div>
        <div class="form-group">
            <input type="number" name="segundoNumero" class="form-control" placeholder="Ingrese el segundo número" />
        </div>
            <input type="submit" class="btn btn-primary" value="Sumar" />
    </form>
</div>

WebApplicationOne/WebApplicationOne/Views/Calculos/Sumar.cshtml
@{
    ViewData["Title"] = "Suma";
}

<p>El resultado es: @ViewData["Resultado"]</p>
<p>El resultado desde el body es: @ViewData["ResultadoFromBody"]</p>

WebApplicationOne/WebApplicationOne/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Inicio";
}

<div class="text-center">
    <h1 class="display-4">Bienvenido</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplicationOne/WebApplicationOne/Views/Mountains/Create.cshtml
@model WebApplicationOne.Entities.Mountain

<h4>Mountain</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Altitud" class="control-label"></label>
                <input asp-for="Altitud" class="form-control" />
                <span asp-validation-for="Altitud" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplicationOne/WebApplicationOne/Views/Mountains/Index.cshtml
@model IEnumerable<WebApplicationOne.Entities.Mountain>
@using WebApplicationOne.Entities
@{
    ViewData["Title"] = "Lista de montañas";
}

<h3>Lista de montañas</h3>
<hr />
@if (!Model.Any())
{
    <p>No hay montañanas registradas</p>
}
<a href="/mountains/create" class="btn btn-primary">Registrar una nueva montaña</a>
<table class="table table-dark">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Altitud</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Mountain actual in Model)
        {
            <tr>
                <td>
                    @(actual.Nombre)
                </td>
                <td>
                    @(actual.Altitud)
                </td>
            </tr>
        }
    </tbody>
</table>

WebApplicationOne/WebApplicationOne/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplicationOne</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplicationOne</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculos" asp-action="Index">Cálculos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mountains" asp-action="Index">Montañas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebApplicationOne - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>